---
apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: config-watcher
      namespace: default
    spec:
      selector:
        matchLabels:
          app: config-watcher
      template:
        metadata:
          labels:
            app: config-watcher
        spec:
          serviceAccount: starter_service
          containers:
          - name: configuration-watcher-container
            image: springcloud/spring-cloud-kubernetes-configuration-watcher:3.1.0-SNAPSHOT
            imagePullPolicy: IfNotPresent
            readinessProbe:
              httpGet:
                port: 8888
                path: /actuator/health/readiness
            livenessProbe:
              httpGet:
                port: 8888
                path: /actuator/health/liveness
            ports:
            - containerPort: 8888
